[package]
name = "day-01"
version = "0.1.0"
authors = ["Tarek Allam <t.allam.jr@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
