# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
name: aoc

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.7.8

  - pip:
    - pytest
    - pytest-cov
    - pytest-subtests
    - pep517
    - twine
    # - -r file:requirements.txt
